### ISSUE TITLE
Add Space to Header

### ISSUE THREAD

**Issue by SafeDuck** [acm-ucr/hiss-website#51]
![image](https://github.com/acm-ucr/hiss-website/assets/49844738/ccd53756-5cac-4fbb-a8c4-82741d994f16)

add the slightest bit of space between the words and line

**Comment by kavinphab** [comment]
![image](https://github.com/acm-ucr/hiss-website/assets/29679531/c75463f1-0999-43e6-b76d-74497e3ce0ac)
desktop

**Comment by kavinphab** [comment]
![image](https://github.com/acm-ucr/hiss-website/assets/29679531/0029af9f-729f-4b68-8292-ecc5615574c9)
iphone XR, should I decrease the the top margin for the title it seems a little low on the page on mobile
