### ISSUE TITLE
animate join cards on scroll

### ISSUE THREAD

**Issue by SafeDuck** [acm-ucr/hiss-website#68]
![image](https://github.com/acm-ucr/hiss-website/assets/49844738/2385e9f0-94b1-4052-842f-bba241f4a76f)

check out PAD website for an example: https://pad.ucrhighlanders.org/events

I know that you can't screenshot an animation, so you don't need one for this

**Comment by achen409** [comment]
i'm not sure what you want me to add.

**Comment by SafeDuck** [comment]
> i'm not sure what you want me to add.

A fade in on scroll

Look at this code here: https://github.com/acm-ucr/pad-website/blob/dev/src/components/events/EventDescription.jsx

You don't need to follow the animation exactly like on the pad website. Just do some kind of animation on scroll.
